type Mutation {
  forgotPassword(
    arg1: Input2!
  ): Output2!
}

type Query {
  getCloudinarySignature(
    arg1: CloudinaryInput!
  ): CloudinaryOutput!
}

type Mutation {
  loginUser(
    arg1: AuthInput!
  ): LoginOutput!
}

type Mutation {
  passwordReset(
    inputs: newInputs!
  ): Output2
}

type Mutation {
  resendCode(
    arg1: ResendCodeInput!
  ): Output2!
}

type Mutation {
  signupUser(
    arg1: SignInput!
  ): Output2!
}

type Mutation {
  verifyEmail(
    verCode: VerificationInput!
  ): output
}

type Mutation {
  verifyResetCode(
    verCode: VerificationInput2!
  ): output
}

input userCredentials {
  email: String!
  password: String!
}

input Input {
  fullName: String!
  email: String!
  password: String!
  avater_url: String
}

input VerificationData {
  email: String!
  code: String!
}

input VerificationInput {
  email: String!
  code: String!
}

input newInputs {
  newPassword: String!
  confirmNewPassowrd: String!
  email: String!
  secretCode: String!
}

input Input2 {
  email: String!
}

input VerificationInput2 {
  email: String!
  code: String!
}

input ResendCodeInput {
  email: String!
  actionType: String!
}

input CloudinaryInput {
  folder: String!
}

input AuthInput {
  email: String!
  password: String!
}

input SignInput {
  email: String!
  password: String!
  name: String!
  avatarUrl: String
}

type Token {
  accessToken: String!
}

type Output {
  message: String!
  code: String
}

type output {
  success: Boolean
  message: String!
  code: String
}

type Response {
  message: String!
}

type Output2 {
  success: Boolean
  message: String!
  code: String
}

type output2 {
  message: String!
  data: String
}

type response {
  timestamp: String!
  signature: String!
}

type CloudinaryOutput {
  message: String
  data: String!
}

type LoginOutput {
  message: String
  code: String
  token: String!
}

